import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        secondary: "#a63500",
        "on-primary-fixed": "#001b3c",
        "secondary-container": "#d04400",
        "on-background": "#1c1b1b",
        primary: "#001e40",
        "secondary-fixed": "#ffdbcf",
        "on-error-container": "#93000a",
        "on-primary-container": "#799dd6",
        "surface-container-highest": "#e5e2e1",
        "tertiary-container": "#313335",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0eded",
        "on-secondary-container": "#fffbff",
        "secondary-fixed-dim": "#ffb59c",
        "on-secondary-fixed-variant": "#822700",
        "primary-fixed": "#d5e3ff",
        error: "#ba1a1a",
        outline: "#737780",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#9a9b9d",
        surface: "#fcf9f8",
        "inverse-primary": "#a7c8ff",
        "error-container": "#ffdad6",
        "primary-container": "#003366",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#390c00",
        "surface-bright": "#fcf9f8",
        "surface-container-high": "#eae7e7",
        "tertiary-fixed-dim": "#c6c6c8",
        "outline-variant": "#c3c6d1",
        "inverse-surface": "#313030",
        "on-tertiary-fixed": "#1a1c1d",
        "surface-variant": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        background: "#fcf9f8",
        "on-tertiary-fixed-variant": "#454749",
        "surface-tint": "#3a5f94",
        "on-surface": "#1c1b1b",
        "tertiary-fixed": "#e2e2e4",
        "on-primary-fixed-variant": "#1f477b",
        tertiary: "#1c1e20",
        "primary-fixed-dim": "#a7c8ff",
        "on-surface-variant": "#43474f",
        "on-primary": "#ffffff",
        cta: "#FF5500",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        button: ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        button: [
          "16px",
          { lineHeight: "1", fontWeight: "600" },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
