import type { FaqItem } from "./types";

export type BuildingStock = "apartman" | "villa-site" | "sanayi-karisik" | "tarihi";
export type DriveTimeBand = "15-25 dk" | "25-40 dk" | "40+ dk";

export type MahalleSeed = {
  slug: string;
  name: string;
  parentIlce: "eyupsultan";
  latitude: number;
  longitude: number;
  distanceKmAir: number;
  driveTimeBand: DriveTimeBand;
  buildingStock: BuildingStock;
  klimaAccessNote: string;
  kombiNote?: string;
  nearbyMahalleler: string[];
  localProfile: string;
  planningNote: string;
  faqs: FaqItem[];
  indexable: boolean;
  group: "merkez-rami" | "kuzey" | "tarihi" | "ofis-yakini" | "gokturk-yakini" | "bati" | "alibeykoy-band";
};

export const EYUPSULTAN_MAHALLE_SEEDS: MahalleSeed[] = [
  {
    slug: "rami",
    name: "Rami",
    parentIlce: "eyupsultan",
    latitude: 41.0442,
    longitude: 28.9285,
    distanceKmAir: 4.5,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Rami bandında yoğun apartman stoğu ve eski tesisat hatları görülür. Rami Cuma ve Rami Yeni hattında iç ünite çoğunlukla balkon veya mutfak duvarına monte edilir; dış ünite için dar merdiven veya balkon köşesi planlanır.",
    kombiNote: "Kombi petek dengesizliği ve basınç kaybı eski dairelerde sık raporlanır; baca hattı kontrolü randevu notuna eklenir.",
    nearbyMahalleler: ["silahtaraga", "defterdar", "nisanca"],
    localProfile: "Rami, Eyüpsultanın güneydoğusunda sanayi ve konutun iç içe geçtiği bir mahalledir. 1970-90 dönemi apartmanlarında kombi dönüşümü sonrası beyaz eşya yenileme talepleri artmıştır. Rami Cuma çarşısı çevresinde ticari birimlerde split klima kullanımı yaygındır. Yoğun trafik saatlerinde Rami Yolu üzerinden servis rotası planlanır. Mahalle sakinleri çoğunlukla aynı gün veya ertesi iş günü randevu talep eder. Klima filtreleri sanayi tozuna maruz kalan cephelerde daha sık temizlenmelidir.",
    planningNote: "Rami adreslerinde sokak adı, bina numarası ve kat bilgisi paylaşıldığında rota netleşir. Dar sokaklarda park için kısa süreli duraklama gerekebilir.",
    faqs: [
      { question: "Rami mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.5 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Rami için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Rami konut tipinde servis planlaması nasıl yapılır?", answer: "Rami mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: true,
    group: "merkez-rami",
  },
  {
    slug: "yesilpinar",
    name: "Yeşilpınar",
    parentIlce: "eyupsultan",
    latitude: 41.0551,
    longitude: 28.9523,
    distanceKmAir: 3.4,
    driveTimeBand: "15-25 dk",
    buildingStock: "sanayi-karisik",
    klimaAccessNote: "Yeşilpınar hattında sanayi tozu ve apartman yoğunluğu bir aradadır; klima filtreleri sezon içinde daha sık temizlenmelidir.",
    kombiNote: "Kombi baca çıkışı ve petek havası alma işlemleri kış öncesi planlanır.",
    nearbyMahalleler: ["emniyettepe", "karadolap", "topcular"],
    localProfile: "Yeşilpınar, Eyüpsultanın kuzeydoğusunda Alibeyköy bağlantı yollarına yakın bir mahalledir. Sanayi bölgesine komşu konutlarda toz birikimi klima performansını düşürür. Apartman stokunda 8-12 katlı binalar yaygındır; asansör kapasitesi dış ünite taşımada önemlidir. Emniyettepe ile birlikte aynı servis bandında değerlendirilir. Yaz aylarında soğutma şikayetleri ve filtre tıkanıklığı öne çıkar.",
    planningNote: "Yeşilpınar randevularında cadde yoğunluğu ve otopark durumu önceden not edilir; sabah erken saatler tercih edilebilir.",
    faqs: [
      { question: "Yeşilpınar mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.4 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Yeşilpınar için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Yeşilpınar konut tipinde servis planlaması nasıl yapılır?", answer: "Yeşilpınar mahallesinde baskın konut tipi sanayi karisik profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: true,
    group: "alibeykoy-band",
  },
  {
    slug: "kemerburgaz",
    name: "Kemerburgaz",
    parentIlce: "eyupsultan",
    latitude: 41.0882,
    longitude: 28.9148,
    distanceKmAir: 2.1,
    driveTimeBand: "25-40 dk",
    buildingStock: "villa-site",
    klimaAccessNote: "Kemerburgazda villa ve site projelerinde dış ünite çatı, bahçe veya teknik oda konumunda olabilir; uzun drenaj hatları kontrol listesindedir.",
    kombiNote: "Kombi ve yerden ısıtma sistemleri villalarda farklı marka kombinasyonlarıyla karşılaşılır.",
    nearbyMahalleler: ["odayeri", "pirincci", "agacli"],
    localProfile: "Kemerburgaz, Eyüpsultanın kuzeyinde orman bandına yakın villa ve site yerleşimlerinin yoğun olduğu bir mahalledir. Geniş parsellerde dış ünite gürültü mesafesi ve komşuluk kuralları dikkate alınır. Kemerburgaz Yolu trafiği özellikle akşam saatlerinde servis varış aralığını etkiler. İlçe klima money sayfası üzerinden randevu alınır; mahalle hub planlama notları burada tutulur.",
    planningNote: "Kemerburgaz adreslerinde site adı, blok ve dış ünite konumu (çatı/bahçe) paylaşılmalıdır.",
    faqs: [
      { question: "Kemerburgaz mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 2.1 km (kuş uçuşu) mesafededir. Trafik bandı genelde 25-40 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Kemerburgaz için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Kemerburgaz konut tipinde servis planlaması nasıl yapılır?", answer: "Kemerburgaz mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: true,
    group: "kuzey",
  },
  {
    slug: "emniyettepe",
    name: "Emniyettepe",
    parentIlce: "eyupsultan",
    latitude: 41.0524,
    longitude: 28.9451,
    distanceKmAir: 3.5,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Emniyettepede yoğun apartman yapısında iç ünite salon veya yatak odası duvarına monte edilir; drenaj için balkon eğimi kontrol edilir.",
    kombiNote: "Kombi arızalarında petek sonu vanası ve genleşme tankı basıncı sık kontrol edilir.",
    nearbyMahalleler: ["yesilpinar", "rami", "merkez"],
    localProfile: "Emniyettepe, Yeşilpınar bandına komşu, yoğun konut dokusuna sahip bir mahalledir. Polis lojmanları ve eski apartman stokunda tesisat yenileme sonrası servis talepleri artar. Kışın kombi basınç düşüklüğü, yazın klima soğutmama şikayetleri öne çıkar. Alibeyköy ofisine kuş uçuşu yakın mesafede olduğu için aynı gün slot sık açılır.",
    planningNote: "Emniyettepe randevularında bina girişi ve asansör durumu önceden bildirilmelidir.",
    faqs: [
      { question: "Emniyettepe mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.5 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Emniyettepe için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Emniyettepe konut tipinde servis planlaması nasıl yapılır?", answer: "Emniyettepe mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: true,
    group: "alibeykoy-band",
  },
  {
    slug: "merkez",
    name: "Merkez",
    parentIlce: "eyupsultan",
    latitude: 41.0489,
    longitude: 28.9344,
    distanceKmAir: 3.9,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Eyüpsultan Merkez mahallelerinde tarihi doku ve apartman karışımı vardır; iç ünite genelde cephe balkonuna bakar.",
    kombiNote: "Eski bina stokunda kombi baca adaptörü ve tesisat uyumluluğu kontrol edilir.",
    nearbyMahalleler: ["aksemsettin", "mithatpasa", "mimar-sinan"],
    localProfile: "Eyüpsultan Merkez, ilçe idari ve ticari odak noktasına yakın mahalleler bütünüdür. Tarihi camii çevresinde dar sokaklar servis aracı erişimini etkileyebilir. Merkez mahalle sakinleri klima bakımını genellikle yaz öncesi planlar. İlçe hub sayfasından tüm hizmet money linklerine geçilebilir.",
    planningNote: "Merkez adreslerinde sokak tarifi ve yakın landmark paylaşımı randevu saatini netleştirir.",
    faqs: [
      { question: "Merkez mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.9 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Merkez için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Merkez konut tipinde servis planlaması nasıl yapılır?", answer: "Merkez mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: true,
    group: "tarihi",
  },
  {
    slug: "silahtaraga",
    name: "Silahtarağa",
    parentIlce: "eyupsultan",
    latitude: 41.0431,
    longitude: 28.9312,
    distanceKmAir: 4.6,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Silahtarağada Rami bandıyla benzer apartman stoğu vardır; eski drenaj hatlarında tıkanıklık sık görülür.",
    kombiNote: "Kombi peteklerinde üst kat alt kat ısı farkı şikayetleri kışın artar.",
    nearbyMahalleler: ["rami", "defterdar", "nisanca"],
    localProfile: "Silahtarağa, Rami ve Defterdar arasında konut yoğunluğu yüksek bir mahalledir. Sanayi atölyelerine yakınlık nedeniyle filtre kirlenmesi hızlanabilir. Apartmanların çoğunda doğalgazlı kombi kullanılır; periyodik bakım talepleri kış öncesi yoğunlaşır. Servis planlaması Rami hattıyla birlikte yapılır.",
    planningNote: "Silahtarağa randevularında cadde kapanışları ve okul çıkış saatleri trafiği dikkate alınır.",
    faqs: [
      { question: "Silahtarağa mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.6 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Silahtarağa için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Silahtarağa konut tipinde servis planlaması nasıl yapılır?", answer: "Silahtarağa mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "merkez-rami",
  },
  {
    slug: "defterdar",
    name: "Defterdar",
    parentIlce: "eyupsultan",
    latitude: 41.0472,
    longitude: 28.9321,
    distanceKmAir: 4.1,
    driveTimeBand: "15-25 dk",
    buildingStock: "tarihi",
    klimaAccessNote: "Defterdar mahallesinde tarihi bina ve apartman karışımında iç ünite montajı duvar kalınlığına göre değerlendirilir.",
    kombiNote: "Eski baca deliklerinde kombi uyumluluğu ve baca çekişi kontrol edilir.",
    nearbyMahalleler: ["rami", "nisanca", "aksemsettin"],
    localProfile: "Defterdar, Eyüpsultan tarihi merkezine yakın, dar sokaklı bir mahalledir. Restore edilmiş binalarda modern klima üniteleri eski elektrik panosuyla uyumsuzluk gösterebilir. Mahalle sakinleri kombi ve klima taleplerini genellikle aynı adres için birleştirir. Tarihi doku nedeniyle dış ünite görünürlük kuralları site yönetiminde sorulmalıdır.",
    planningNote: "Defterdar adreslerinde bina giriş kapısı kodu ve kat bilgisi randevu öncesi paylaşılmalıdır.",
    faqs: [
      { question: "Defterdar mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.1 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Defterdar için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Defterdar konut tipinde servis planlaması nasıl yapılır?", answer: "Defterdar mahallesinde baskın konut tipi tarihi profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
  {
    slug: "aksemsettin",
    name: "Akşemsettin",
    parentIlce: "eyupsultan",
    latitude: 41.0453,
    longitude: 28.9422,
    distanceKmAir: 4.3,
    driveTimeBand: "15-25 dk",
    buildingStock: "tarihi",
    klimaAccessNote: "Akşemsettin çevresinde tarihi konutlarda split klima montajı için duvar taşıyıcı analizi önemlidir.",
    kombiNote: "Kombi baca hattı eski binalarda düşey kanal ile çözülür; çekiş testi yapılır.",
    nearbyMahalleler: ["merkez", "mithatpasa", "islambey"],
    localProfile: "Akşemsettin, Eyüpsultanın tarihi çekirdeğine yakın mahallelerden biridir. Dar sokaklar ve yüksek eğimli yollar servis aracı rotasını etkiler. Apartman dairelerinde salon tipi klima ile split sistem bir arada kullanılabilir. Mahalle adı ilçe tarihi kimliğiyle özdeşleşmiştir.",
    planningNote: "Akşemsettin randevularında yakın camii veya okul landmarkı tarif için yeterlidir.",
    faqs: [
      { question: "Akşemsettin mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.3 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Akşemsettin için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Akşemsettin konut tipinde servis planlaması nasıl yapılır?", answer: "Akşemsettin mahallesinde baskın konut tipi tarihi profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
  {
    slug: "mithatpasa",
    name: "Mithatpaşa",
    parentIlce: "eyupsultan",
    latitude: 41.0441,
    longitude: 28.9384,
    distanceKmAir: 4.4,
    driveTimeBand: "15-25 dk",
    buildingStock: "tarihi",
    klimaAccessNote: "Mithatpaşada iç ünite genelde oturma odası duvarına monte edilir; dış ünite balkon altına sığmayabilir.",
    kombiNote: "Kombi odası küçük dairelerde hava sirkülasyonu için havalandırma kontrol edilir.",
    nearbyMahalleler: ["merkez", "aksemsettin", "dugmeciler"],
    localProfile: "Mithatpaşa, ilçe merkezine komşu, orta yoğunlukta apartman mahallesidir. Eski bina stokunda tesisat yenileme sonrası beyaz eşya arızaları artabilir. Yazın klima bakım talepleri, kışın kombi servisi talepleri dengeli dağılır. Mahalle sakinleri çoğunlukla telefon veya WhatsApp üzerinden randevu oluşturur.",
    planningNote: "Mithatpaşa adreslerinde apartman adı varsa paylaşılması teknisyen yönlendirmesini hızlandırır.",
    faqs: [
      { question: "Mithatpaşa mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.4 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Mithatpaşa için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Mithatpaşa konut tipinde servis planlaması nasıl yapılır?", answer: "Mithatpaşa mahallesinde baskın konut tipi tarihi profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
  {
    slug: "nisanca",
    name: "Nişanca",
    parentIlce: "eyupsultan",
    latitude: 41.0461,
    longitude: 28.9263,
    distanceKmAir: 4.3,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Nişancada Rami bandı apartmanlarında drenaj hortumu eğimi ve balkon süzgeci temizliği önemlidir.",
    kombiNote: "Kombi genleşme tankı basıncı ve emniyet ventili kış kontrol listesindedir.",
    nearbyMahalleler: ["rami", "silahtaraga", "defterdar"],
    localProfile: "Nişanca, Rami yönünde konut yoğunluğu olan bir mahalledir. Sanayi bölgesine yakınlık klima filtrelerinde erken kirlenmeye yol açabilir. Apartman yönetimleri bazen dış ünite saat kısıtı uygular; randevu notuna eklenir. Servis ekibi mahalle içi tek yön sokaklara dikkat eder.",
    planningNote: "Nişanca randevularında araç park alanı tarifi kısaltır.",
    faqs: [
      { question: "Nişanca mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.3 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Nişanca için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Nişanca konut tipinde servis planlaması nasıl yapılır?", answer: "Nişanca mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "merkez-rami",
  },
  {
    slug: "odayeri",
    name: "Odayeri",
    parentIlce: "eyupsultan",
    latitude: 41.0951,
    longitude: 28.9024,
    distanceKmAir: 3.3,
    driveTimeBand: "40+ dk",
    buildingStock: "villa-site",
    klimaAccessNote: "Odayeride kırsal-site karışımında dış ünite uzak konumda olabilir; hat uzunluğu ve izolasyon kontrol edilir.",
    kombiNote: "Kombi ve şömine sistemleri villalarda farklı ısıtma senaryoları oluşturur.",
    nearbyMahalleler: ["kemerburgaz", "pirincci", "ciftalan"],
    localProfile: "Odayeri, Kemerburgaz kuzeyinde doğaya yakın villa yerleşimlerinin bulunduğu bir mahalledir. Orman yangını riski dönemlerinde dış ünite çevre temizliği hatırlatılır. Yol kalitesi mevsime göre değişir; kış randevularında erken saat önerilir. İlçe klima sayfası üzerinden genel randevu alınır.",
    planningNote: "Odayeri adreslerinde GPS pin ve site güvenlik telefonu paylaşılmalıdır.",
    faqs: [
      { question: "Odayeri mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.3 km (kuş uçuşu) mesafededir. Trafik bandı genelde 40+ dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Odayeri için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Odayeri konut tipinde servis planlaması nasıl yapılır?", answer: "Odayeri mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "kuzey",
  },
  {
    slug: "pirincci",
    name: "Pirinççi",
    parentIlce: "eyupsultan",
    latitude: 41.0923,
    longitude: 28.9081,
    distanceKmAir: 2.8,
    driveTimeBand: "25-40 dk",
    buildingStock: "villa-site",
    klimaAccessNote: "Pirinççide site içi dış ünite çatı veya bahçe duvarına monte edilir; site yönetim kuralları uygulanır.",
    kombiNote: "Yerden ısıtma ve kombi kombinasyonları site projelerinde yaygındır.",
    nearbyMahalleler: ["kemerburgaz", "odayeri", "agacli"],
    localProfile: "Pirinççi, Kemerburgaz hattında yeni konut projeleri ve villaların karıştığı bir mahalledir. TEM bağlantı yolu trafiği öğleden sonra yoğunlaşır. Mahalle sakinleri klima bakımını genellikle yaz öncesi toplu planlar. Göktürk spoke sayfası kuzey villa notları için tamamlayıcıdır.",
    planningNote: "Pirinççi site adreslerinde blok ve daire numarası zorunludur.",
    faqs: [
      { question: "Pirinççi mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 2.8 km (kuş uçuşu) mesafededir. Trafik bandı genelde 25-40 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Pirinççi için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Pirinççi konut tipinde servis planlaması nasıl yapılır?", answer: "Pirinççi mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "kuzey",
  },
  {
    slug: "agacli",
    name: "Ağaçlı",
    parentIlce: "eyupsultan",
    latitude: 41.0982,
    longitude: 28.8953,
    distanceKmAir: 4.0,
    driveTimeBand: "40+ dk",
    buildingStock: "villa-site",
    klimaAccessNote: "Ağaçlıda geniş parsellerde dış ünite rüzgar yönü ve gürültü mesafesi planlanır.",
    kombiNote: "Kombi odası havalandırması villalarda ayrı teknik hacimde olabilir.",
    nearbyMahalleler: ["ciftalan", "odayeri", "kemerburgaz"],
    localProfile: "Ağaçlı, Eyüpsultanın en kuzey mahallelerinden biridir. Orman bandına yakınlık nem ve polen birikimini artırır; filtre bakımı öne çıkar. Kış aylarında yol koşulları varış aralığını genişletebilir. Mahalle hub sayfası planlama amaçlıdır; para sorguları ilçe klima sayfasına yönlendirilir.",
    planningNote: "Ağaçlı villalarında kapı kodu ve köpek durumu önceden bildirilmelidir.",
    faqs: [
      { question: "Ağaçlı mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.0 km (kuş uçuşu) mesafededir. Trafik bandı genelde 40+ dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Ağaçlı için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Ağaçlı konut tipinde servis planlaması nasıl yapılır?", answer: "Ağaçlı mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "kuzey",
  },
  {
    slug: "ciftalan",
    name: "Çiftalan",
    parentIlce: "eyupsultan",
    latitude: 41.1021,
    longitude: 28.8882,
    distanceKmAir: 4.7,
    driveTimeBand: "40+ dk",
    buildingStock: "villa-site",
    klimaAccessNote: "Çiftalande seyrek yerleşimde dış ünite geniş bahçede konumlanır; güneş ve yağmur koruması kontrol edilir.",
    kombiNote: "Kombi ve kalorifer sistemleri büyük villalarda çoklu devre gerektirebilir.",
    nearbyMahalleler: ["agacli", "odayeri", "pirincci"],
    localProfile: "Çiftalan, Eyüpsultan sınırında kırsal karakterli bir mahalledir. Konut yoğunluğu düşük olduğu için servis rotası Kemerburgaz üzerinden planlanır. Yazın villa klimaları uzun süre kapalı kaldığında ilk çalıştırmada koku şikayeti görülebilir.",
    planningNote: "Çiftalan adreslerinde yol açıklaması ve telefon sinyali zayıf noktaları not edilir.",
    faqs: [
      { question: "Çiftalan mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.7 km (kuş uçuşu) mesafededir. Trafik bandı genelde 40+ dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Çiftalan için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Çiftalan konut tipinde servis planlaması nasıl yapılır?", answer: "Çiftalan mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "kuzey",
  },
  {
    slug: "5-levent",
    name: "5. Levent",
    parentIlce: "eyupsultan",
    latitude: 41.0782,
    longitude: 28.9951,
    distanceKmAir: 4.7,
    driveTimeBand: "25-40 dk",
    buildingStock: "villa-site",
    klimaAccessNote: "5. Leventte rezidans ve villa karışımında dış ünite çatı terası veya bahçe duvarında olabilir.",
    kombiNote: "Kombi ve merkezi sistem ayrımı site projelerinde netleştirilir.",
    nearbyMahalleler: ["isiklar", "gokturk"],
    localProfile: "5. Levent, Göktürk semtine komşu lüks konut bandıdır. Göktürk klima spoke sayfası semt detayını taşır; bu mahalle hub planlama notları içindir. TEM ve Kemer Country bağlantı yolları trafiği randevu penceresini etkiler.",
    planningNote: "5. Levent site girişinde ziyaretçi kaydı için daire numarası ve plaka paylaşılmalıdır.",
    faqs: [
      { question: "5. Levent mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.7 km (kuş uçuşu) mesafededir. Trafik bandı genelde 25-40 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "5. Levent için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "5. Levent konut tipinde servis planlaması nasıl yapılır?", answer: "5. Levent mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "gokturk-yakini",
  },
  {
    slug: "isiklar",
    name: "Işıklar",
    parentIlce: "eyupsultan",
    latitude: 41.0821,
    longitude: 28.9852,
    distanceKmAir: 3.9,
    driveTimeBand: "25-40 dk",
    buildingStock: "villa-site",
    klimaAccessNote: "Işıklarda villa ve düşük yoğunluklu apartmanlarda dış ünite bahçe veya çatıda konumlanır.",
    kombiNote: "Kombi bakımı kış öncesi villalarda yoğunlaşır.",
    nearbyMahalleler: ["5-levent", "gokturk", "kemerburgaz"],
    localProfile: "Işıklar, Göktürk kuzeyinde konut projelerinin yayıldığı bir mahalledir. Göktürk spoke sayfası klima money hedefidir; mahalle hub erişim ve konut tipi notlarını tutar. Orman hattına yakınlık filtre bakımını öne çıkarır.",
    planningNote: "Işıklar adreslerinde site veya villa adı ve dış ünite konumu belirtilmelidir.",
    faqs: [
      { question: "Işıklar mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.9 km (kuş uçuşu) mesafededir. Trafik bandı genelde 25-40 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Işıklar için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Işıklar konut tipinde servis planlaması nasıl yapılır?", answer: "Işıklar mahallesinde baskın konut tipi villa site profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "gokturk-yakini",
  },
  {
    slug: "circir",
    name: "Çırçır",
    parentIlce: "eyupsultan",
    latitude: 41.0512,
    longitude: 28.9183,
    distanceKmAir: 4.0,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Çırçırda apartman stoğunda iç ünite mutfak-balkon hattına yakındır; drenaj tıkanıklığı sık görülür.",
    kombiNote: "Kombi petek havası alma işlemi kış başında planlanır.",
    nearbyMahalleler: ["akpinar", "esentepe", "sakarya"],
    localProfile: "Çırçır, Eyüpsultanın batısında konut yoğunluğu olan bir mahalledir. Eski sanayi alanlarına dönüşüm projeleri yeni apartman stokunu artırmıştır. Mahalle sakinleri beyaz eşya ve klima taleplerini birlikte planlayabilir.",
    planningNote: "Çırçır randevularında ana cadde üzerinden sokak girişi tarif edilmelidir.",
    faqs: [
      { question: "Çırçır mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.0 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Çırçır için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Çırçır konut tipinde servis planlaması nasıl yapılır?", answer: "Çırçır mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "bati",
  },
  {
    slug: "esentepe",
    name: "Esentepe",
    parentIlce: "eyupsultan",
    latitude: 41.0501,
    longitude: 28.9224,
    distanceKmAir: 4.0,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Esentepe apartmanlarında salon tipi ve split klima bir arada kullanılabilir.",
    kombiNote: "Kombi basınç göstergesi düşükse önce kaçak testi önerilir.",
    nearbyMahalleler: ["circir", "sakarya", "akpinar"],
    localProfile: "Esentepe, Çırçır ve Sakarya arasında orta yoğunlukta bir mahalledir. Apartmanların çoğu 1990 sonrası inşa edilmiştir. Yazın klima gaz kontrolü talepleri artar. İlçe hub üzerinden kombi ve beyaz eşya money sayfalarına geçilebilir.",
    planningNote: "Esentepe adreslerinde bina numarası ve daire kapı kodu paylaşılmalıdır.",
    faqs: [
      { question: "Esentepe mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.0 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Esentepe için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Esentepe konut tipinde servis planlaması nasıl yapılır?", answer: "Esentepe mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "bati",
  },
  {
    slug: "sakarya",
    name: "Sakarya",
    parentIlce: "eyupsultan",
    latitude: 41.0492,
    longitude: 28.9251,
    distanceKmAir: 4.0,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Sakaryada iç ünite yatak odası veya çocuk odası duvarında monte edilebilir.",
    kombiNote: "Kombi odası havalandırma ızgarası toz birikimine karşı kontrol edilir.",
    nearbyMahalleler: ["esentepe", "merkez", "ihsaniye"],
    localProfile: "Sakarya, ilçe merkezine yakın, sakin konut mahallesidir. Aile hanelerinde çamaşır makinesi ve bulaşık makinesi arızaları sık bildirilir. Klima bakımı genellikle Nisan-Mayıs döneminde planlanır.",
    planningNote: "Sakarya randevularında sokak adı ve yakın durak landmarkı yeterlidir.",
    faqs: [
      { question: "Sakarya mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.0 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Sakarya için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Sakarya konut tipinde servis planlaması nasıl yapılır?", answer: "Sakarya mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "bati",
  },
  {
    slug: "akpinar",
    name: "Akpınar",
    parentIlce: "eyupsultan",
    latitude: 41.0562,
    longitude: 28.9152,
    distanceKmAir: 3.7,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Akpınarda yeni yapı apartmanlarda inverter klima yaygındır; ilk sezon bakımı önemlidir.",
    kombiNote: "Kombi marka çeşitliliği yeni binalarda yüksektir.",
    nearbyMahalleler: ["circir", "esentepe", "topcular"],
    localProfile: "Akpınar, batı Eyüpsultan hattında gelişen konut alanıdır. Genç ailelerin yoğun olduğu mahallede beyaz eşya kurulum sonrası ilk arıza talepleri görülür. Servis rotası Çırçır üzerinden planlanır.",
    planningNote: "Akpınar yeni sitelerinde güvenlik kaydı için daire numarası gereklidir.",
    faqs: [
      { question: "Akpınar mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.7 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Akpınar için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Akpınar konut tipinde servis planlaması nasıl yapılır?", answer: "Akpınar mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "bati",
  },
  {
    slug: "ihsaniye",
    name: "İhsaniye",
    parentIlce: "eyupsultan",
    latitude: 41.0471,
    longitude: 28.9362,
    distanceKmAir: 4.1,
    driveTimeBand: "15-25 dk",
    buildingStock: "tarihi",
    klimaAccessNote: "İhsaniyede tarihi-apartman karışımında iç ünite montaj noktası duvar malzemesine göre seçilir.",
    kombiNote: "Eski kombi baca deliklerinde sızdırmazlık kontrol edilir.",
    nearbyMahalleler: ["merkez", "sakarya", "islambey"],
    localProfile: "İhsaniye, ilçe merkezine komşu, tarihi dokuya yakın bir mahalledir. Restore binalarda elektrik panosu kapasitesi klima kurulumunu etkileyebilir. Mahalle sakinleri kombi bakımını kış öncesi planlar.",
    planningNote: "İhsaniye adreslerinde bina giriş tarifi ve kat bilgisi paylaşılmalıdır.",
    faqs: [
      { question: "İhsaniye mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.1 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "İhsaniye için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "İhsaniye konut tipinde servis planlaması nasıl yapılır?", answer: "İhsaniye mahallesinde baskın konut tipi tarihi profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
  {
    slug: "islambey",
    name: "İslambey",
    parentIlce: "eyupsultan",
    latitude: 41.0432,
    longitude: 28.9341,
    distanceKmAir: 4.6,
    driveTimeBand: "15-25 dk",
    buildingStock: "tarihi",
    klimaAccessNote: "İslambeyde tarihi konutlarda split klima için uygun montaj noktası yerinde belirlenir.",
    kombiNote: "Kombi baca çekişi eski binalarda düşük olabilir; ölçüm yapılır.",
    nearbyMahalleler: ["aksemsettin", "ihsaniye", "dugmeciler"],
    localProfile: "İslambey, Eyüpsultan tarihi merkez bandının parçasıdır. Dar sokaklar ve park kısıtı randevu saatini etkiler. Turistik yoğunluk dönemlerinde trafik alternatif rotalarla çözülür.",
    planningNote: "İslambey randevularında yakın camii veya meydan tarifi yeterlidir.",
    faqs: [
      { question: "İslambey mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.6 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "İslambey için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "İslambey konut tipinde servis planlaması nasıl yapılır?", answer: "İslambey mahallesinde baskın konut tipi tarihi profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
  {
    slug: "dugmeciler",
    name: "Düğmeciler",
    parentIlce: "eyupsultan",
    latitude: 41.0421,
    longitude: 28.9302,
    distanceKmAir: 4.7,
    driveTimeBand: "15-25 dk",
    buildingStock: "tarihi",
    klimaAccessNote: "Düğmecilerde eski apartmanlarda drenaj hattı eğimi yetersiz olabilir; su damlatma şikayeti görülür.",
    kombiNote: "Kombi petek temizliği kış öncesi önerilir.",
    nearbyMahalleler: ["islambey", "mithatpasa", "nisanca"],
    localProfile: "Düğmeciler, tarihi Eyüpsultan dokusunun yoğun olduğu küçük bir mahalledir. Eski tesisat hatları beyaz eşya arızalarını tetikleyebilir. Mahalle adı küçük sanayi atölyeleriyle özdeşleşmiştir.",
    planningNote: "Düğmeciler dar sokaklarında araç bekleme noktası telefonla netleştirilir.",
    faqs: [
      { question: "Düğmeciler mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.7 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Düğmeciler için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Düğmeciler konut tipinde servis planlaması nasıl yapılır?", answer: "Düğmeciler mahallesinde baskın konut tipi tarihi profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
  {
    slug: "guzeltepe",
    name: "Güzeltepe",
    parentIlce: "eyupsultan",
    latitude: 41.0682,
    longitude: 28.9581,
    distanceKmAir: 2.4,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Güzeltepede Alibeyköy spoke bandında apartman yoğunluğu yüksektir; filtre bakımı sık gerekebilir.",
    kombiNote: "Kombi arızalarında petek vanası ve hava purjörü kontrol edilir.",
    nearbyMahalleler: ["karadolap", "topcular", "alibeykoy"],
    localProfile: "Güzeltepe, Alibeyköy semtine bağlı yoğun konut mahallesidir. Alibeyköy klima money sayfası semt detayı içindir; bu sayfa mahalle planlama hubıdır. Ofise kuş uçuşu yakın mesafede olduğu için aynı gün randevu sık açılır.",
    planningNote: "Güzeltepe adreslerinde cadde ve sokak kesişimi tarif edilmelidir.",
    faqs: [
      { question: "Güzeltepe mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 2.4 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Güzeltepe için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Güzeltepe konut tipinde servis planlaması nasıl yapılır?", answer: "Güzeltepe mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "alibeykoy-band",
  },
  {
    slug: "karadolap",
    name: "Karadolap",
    parentIlce: "eyupsultan",
    latitude: 41.0621,
    longitude: 28.9552,
    distanceKmAir: 2.8,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Karadolap hattında apartman balkonlarında dış ünite komşu duvar mesafesi kontrol edilir.",
    kombiNote: "Kombi basınç kaybı tekrarlıyorsa tesisat kaçağı araştırılır.",
    nearbyMahalleler: ["guzeltepe", "topcular", "yesilpinar"],
    localProfile: "Karadolap, Alibeyköy-Yeşilpınar arasında konut yoğunluğu olan bir mahalledir. Yeni doğalgaz dönüşümü sonrası kombi kurulum talepleri artmıştır. Mahalle hub organik planlama içindir.",
    planningNote: "Karadolap randevularında bina numarası ve asansör durumu bildirilmelidir.",
    faqs: [
      { question: "Karadolap mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 2.8 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Karadolap için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Karadolap konut tipinde servis planlaması nasıl yapılır?", answer: "Karadolap mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "alibeykoy-band",
  },
  {
    slug: "topcular",
    name: "Topçular",
    parentIlce: "eyupsultan",
    latitude: 41.0582,
    longitude: 28.9481,
    distanceKmAir: 3.0,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Topçularda sanayi-konut sınırında toz birikimi klima filtrelerini hızla kirletir.",
    kombiNote: "Kombi baca ucu temizliği kış öncesi kontrol listesindedir.",
    nearbyMahalleler: ["karadolap", "guzeltepe", "emniyettepe"],
    localProfile: "Topçular, Alibeyköy bağlantı yoluna yakın, karma kullanımlı bir mahalledir. Ticari birimlerde split klima, konutlarda kombi yoğun kullanılır. Servis planlaması ofis yakını bandında hızlıdır.",
    planningNote: "Topçular adreslerinde ana cadde üzerinden sokak girişi tarif edilmelidir.",
    faqs: [
      { question: "Topçular mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 3.0 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Topçular için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Topçular konut tipinde servis planlaması nasıl yapılır?", answer: "Topçular mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "alibeykoy-band",
  },
  {
    slug: "mimar-sinan",
    name: "Mimar Sinan",
    parentIlce: "eyupsultan",
    latitude: 41.0481,
    longitude: 28.9402,
    distanceKmAir: 4.0,
    driveTimeBand: "15-25 dk",
    buildingStock: "apartman",
    klimaAccessNote: "Mimar Sinanda apartman iç üniteleri genelde salon duvarına monte edilir.",
    kombiNote: "Kombi emniyet ventili ve genleşme tankı basıncı kontrol edilir.",
    nearbyMahalleler: ["merkez", "aksemsettin", "sakarya"],
    localProfile: "Mimar Sinan, ilçe merkezine yakın, orta yoğunlukta konut mahallesidir. Okul ve park çevresinde trafik okul saatlerinde yoğunlaşır. Mahalle sakinleri klima bakımını yaz öncesi planlar.",
    planningNote: "Mimar Sinan randevularında bina giriş kodu paylaşılmalıdır.",
    faqs: [
      { question: "Mimar Sinan mahallesine teknik servis ne kadar sürede ulaşır?", answer: "Alibeyköy ofisine yaklaşık 4.0 km (kuş uçuşu) mesafededir. Trafik bandı genelde 15-25 dk aralığındadır; kesin saat randevu sırasında paylaşılır." },
      { question: "Mimar Sinan için klima randevusu nereden alınır?", answer: "Para niyetli klima talepleri Eyüpsultan klima servisi money sayfasından planlanır. Bu mahalle hub sayfası erişim ve konut tipi planlama notları içindir." },
      { question: "Mimar Sinan konut tipinde servis planlaması nasıl yapılır?", answer: "Mimar Sinan mahallesinde baskın konut tipi apartman profilindedir. Adres, cihaz modeli ve şikâyet özeti paylaşıldığında uygun ekip ve saat aralığı önerilir." },
    ],
    indexable: false,
    group: "tarihi",
  },
];

export const EYUPSULTAN_SPOKE_REDIRECTS: Record<string, string> = {
  Alibeyköy: "/servis-bolgeleri/alibeykoy",
  Göktürk: "/servis-bolgeleri/gokturk",
};

export const MAHALLE_GROUP_LABELS: Record<MahalleSeed["group"], string> = {
  "merkez-rami": "Merkez ve Rami bandı",
  kuzey: "Kuzey (Kemerburgaz, Odayeri)",
  tarihi: "Tarihi merkez",
  "ofis-yakini": "Ofis yakını",
  "gokturk-yakini": "Göktürk yakını",
  bati: "Batı mahalleler",
  "alibeykoy-band": "Alibeyköy bandı",
};
